# Configuración global del pipeline
workflow:
  auto_cancel:
    # Si un job falla, el pipeline se puede interrumpir. Esto es útil para no desperdiciar recursos.
    on_job_failure: interruptible
    # Si se hace un nuevo commit mientras la pipeline anterior aún está corriendo, esa pipeline se interrumpe. Así, solo se ejecuta la versión más reciente.
    on_new_commit: interruptible

  # Reglas para determinar si se debe ejecutar el pipeline
  rules:
    # Si el branch actual es "main", se definen ciertas variables para esta pipeline.
    - if: '$CI_COMMIT_REF_NAME == "main"'
      variables:
        PIPELINE_NAME: "Main pipeline"  # Asigna un nombre a la pipeline principal.

    # Si el branch es un branch de feature (que comience con "feature/"), se definen otras variables.
    - if: '$CI_COMMIT_REF_NAME =~ /^feature\//'
      variables:
        PIPELINE_NAME: "Feature pipeline"  # Asigna un nombre a las pipelines de las ramas de features.

    # Si no cumple ninguna de las reglas anteriores, la pipeline no se ejecuta.
    - when: never  # Esta regla garantiza que el pipeline solo se ejecuta en main o en feature branches.

# Definición de las etapas del pipeline.
# Cada job debe estar asignado a una de estas etapas y se ejecutarán en el orden especificado.
stages:
  - build    # Primera etapa: build (compilación o construcción).
  - test     # Segunda etapa: test.
  - deploy   # Tercera etapa: deploy (despliegue).

########## job_build ##########
job_build:
  stage: build  # Este job pertenece a la etapa "build".
  script:
    - echo 'Building the project...'  # El script principal que se ejecuta es un simple echo, pero aquí podrías compilar o construir tu proyecto.

########## job_test ##########
job_test:
  stage: test  # Este job pertenece a la etapa "test".
  script:
    - echo 'hola'  # De nuevo, un script sencillo que simplemente imprime un mensaje. Normalmente aquí ejecutarías tus pruebas automáticas.

########## job_deploy ##########
job_deploy:
  stage: deploy  # Este job pertenece a la etapa "deploy".
  # Al ser interruptible, si una nueva pipeline comienza (por ejemplo, debido a un nuevo commit), este job puede ser cancelado.
  interruptible: true
  script:
    - echo 'Deploying to production...'  # El script principal que simula el despliegue a producción. En un entorno real, aquí pondrías los comandos necesarios para desplegar tu aplicación.
